name: Build Android APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Environment
        run: |
          sudo apt update
          sudo apt install -y git autoconf libtool pkg-config zlib1g-dev libncurses5-dev libncursesw5-dev libtinfo5 cmake libffi-dev libssl-dev python3-pip python3-venv
          
          # Virtual Environment बनाना (सबसे ज़रूरी स्टेप)
          python3 -m venv venv
          source venv/bin/activate
          pip install --upgrade pip
          pip install buildozer
          
          # Buildozer को पाथ में जोड़ना
          echo "$PWD/venv/bin" >> $GITHUB_PATH

      - name: Build APK
        run: |
          source venv/bin/activate
          buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MediaFinderAPK
          path: bin/*.apk
