name: Build APK
on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: kivy/buildozer:latest
    steps:
      - uses: actions/checkout@v4

      - name: Build APK
        env:
          # यह वेरिएबल Docker कंटेनर के अंदर चेक_रूट को बायपास करेगा
          BUILDOZER_ALLOW_ROOT: 1
        run: |
          # 'yes' कमांड इनपुट के लिए 'y' ऑटोमैटिकली भेजता रहेगा
          yes | buildozer android debug

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: MediaFinderAPK
          path: bin/*.apk
